'use client';

import { Navigation } from '@/components/layout/Navigation';
import { ArrowLeft } from 'lucide-react';
import Link from 'next/link';
import { Button } from '@/components/ui/button';

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-blue-50">
      <Navigation />

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8 sm:py-12">
        {/* Back Button */}
        <div className="mb-6">
          <Link href="/">
            <Button variant="outline" className="text-sm">
              <ArrowLeft className="h-4 w-4 mr-2" />
              Back to Home
            </Button>
          </Link>
        </div>

        {/* Header */}
        <div className="text-center mb-8 sm:mb-12">
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-4">Terms & Conditions</h1>
          <p className="text-sm text-gray-600">Last Updated: September 8, 2025</p>
        </div>

        {/* Content */}
        <div className="prose prose-lg max-w-none bg-white rounded-lg shadow-sm p-6 sm:p-8">
          <p className="text-gray-700 leading-relaxed mb-6">
            Welcome to ListingIQ. By accessing or using this site, you agree to the following Terms.
            If you do not agree, please do not use the service.
          </p>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">1. Nature of Service</h2>
            <p className="text-gray-700 leading-relaxed mb-4">
              ListingIQ is an experimental tool that provides AI-generated property insights based
              on listing descriptions you paste in. It is intended for informational and educational
              purposes only.
            </p>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>We do not provide real estate, legal, investment, or financial advice.</li>
              <li>
                You should always conduct your own research and consult licensed professionals
                before making decisions.
              </li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">2. User Responsibilities</h2>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>You agree to use ListingIQ only for lawful purposes.</li>
              <li>You will not misuse, attempt to hack, or interfere with the service.</li>
              <li>
                You understand that outputs are generated by AI and may contain errors or omissions.
              </li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">3. Limitation of Liability</h2>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>ListingIQ is provided &quot;as is&quot; without warranties of any kind.</li>
              <li>
                We are not liable for any damages, losses, or decisions made based on the use of
                this tool.
              </li>
              <li>Your use of the service is entirely at your own risk.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">4. Accounts & Access</h2>
            <ul className="list-disc list-inside text-gray-700 space-y-2 ml-4">
              <li>
                If you create an account, you are responsible for keeping your login details secure.
              </li>
              <li>We may suspend or terminate access at our discretion.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">5. Changes to Service</h2>
            <p className="text-gray-700 leading-relaxed">
              We may update, modify, or discontinue ListingIQ at any time without notice.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-900 mb-4">6. Governing Law</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms are governed by the laws of the State of New York, United States, without
              regard to conflict of law principles.
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}
